# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airulesync < Formula
  desc "airulesync is a CLI tool for syncing AI coding rules"
  homepage "https://github.com/upamune/airulesync"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/airulesync/releases/download/v0.0.6/airulesync_Darwin_x86_64.tar.gz"
      sha256 "7f5b069eebb5ae1e2ebd904535ac6c033c9cc181a464131dc3b9fac5f299c6fb"

      def install
        bin.install "airulesync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/airulesync/releases/download/v0.0.6/airulesync_Darwin_arm64.tar.gz"
      sha256 "5c60881004ba7ca1b03ebd59c1e2d4590851c73fd84d0506604fb61f81fa6966"

      def install
        bin.install "airulesync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/airulesync/releases/download/v0.0.6/airulesync_Linux_x86_64.tar.gz"
        sha256 "0c9d4a0e25b31d8f9652de63f0b98f80a6bdb75b311698d60266c490ce7e2703"

        def install
          bin.install "airulesync"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/airulesync/releases/download/v0.0.6/airulesync_Linux_arm64.tar.gz"
        sha256 "0f130ae03b29be45c13f2462f202d103a1bfa921b9acb89a5c81afa2e3c3f966"

        def install
          bin.install "airulesync"
        end
      end
    end
  end
end
