# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airule < Formula
  desc "airule is an interactive terminal-based tool for selectively copying rule files between directories."
  homepage "https://github.com/upamune/airule"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/airule/releases/download/v0.0.3/airule_Darwin_amd64.tar.gz"
      sha256 "76f9943636c5ea419e4a3657dbafad6b365c676406c2e6eabf1e0d23f40f90fb"

      def install
        bin.install "airule"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/airule/releases/download/v0.0.3/airule_Darwin_arm64.tar.gz"
      sha256 "576c1e49d150df4eb2dee150b176a4d71b6a70c934b14a9475423beba023912a"

      def install
        bin.install "airule"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/airule/releases/download/v0.0.3/airule_Linux_amd64.tar.gz"
        sha256 "622b2de945ff9a1f170bf5e86ab5e9f65eef342352b4a60d212397b24ab77f99"

        def install
          bin.install "airule"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/airule/releases/download/v0.0.3/airule_Linux_arm64.tar.gz"
        sha256 "a69cc9c0f98a183b98486c201141d9a775d5723a02fcba1b38a2a7b23cb73959"

        def install
          bin.install "airule"
        end
      end
    end
  end
end
