# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airulesync < Formula
  desc "airulesync is a CLI tool for syncing AI coding rules"
  homepage "https://github.com/upamune/airulesync"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/airulesync/releases/download/v0.0.3/airulesync_Darwin_x86_64.tar.gz"
      sha256 "82513a7737724a6c09bd7c722bd8d1b29541b860a47c51c1c7f6bcf2961fdf0a"

      def install
        bin.install "airulesync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/airulesync/releases/download/v0.0.3/airulesync_Darwin_arm64.tar.gz"
      sha256 "7fab5f30170bb83093fbb9fa42bab9118ac9e16a5929ff7ec9e06fa2a0b08487"

      def install
        bin.install "airulesync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/airulesync/releases/download/v0.0.3/airulesync_Linux_x86_64.tar.gz"
        sha256 "da5142d174d34c8a6dc99edb70417f14357fdb8c2a6fd68cbab4614deedf8833"

        def install
          bin.install "airulesync"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/airulesync/releases/download/v0.0.3/airulesync_Linux_arm64.tar.gz"
        sha256 "5a0d11962d46fc3225095fd2b0e527f6e3256ec185e0e768fb79ff8b722cb3f8"

        def install
          bin.install "airulesync"
        end
      end
    end
  end
end
