# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airule < Formula
  desc "airule is an interactive terminal-based tool for selectively copying rule files between directories."
  homepage "https://github.com/upamune/airule"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/airule/releases/download/v0.0.5/airule_Darwin_amd64.tar.gz"
      sha256 "41733c7c69298867aa69b78e8b0ed5889646a5aa998d8fd0a19dd23a78ae106f"

      def install
        bin.install "airule"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/airule/releases/download/v0.0.5/airule_Darwin_arm64.tar.gz"
      sha256 "8943a2acf23ce594ef57204e4cc2b1aa9c16013811d85f1d0921a9417365bba9"

      def install
        bin.install "airule"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/upamune/airule/releases/download/v0.0.5/airule_Linux_amd64.tar.gz"
      sha256 "e48377a1d035f5d39c15e344446b2ce99f1d12f032aab5a14f1d67d0de44a917"
      def install
        bin.install "airule"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/upamune/airule/releases/download/v0.0.5/airule_Linux_arm64.tar.gz"
      sha256 "21e1580eb1c6ef5084556f29e52b5362b05f3fac1d93a6055bea21b47aec633a"
      def install
        bin.install "airule"
      end
    end
  end
end
