# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airule < Formula
  desc "airule is an interactive terminal-based tool for selectively copying rule files between directories."
  homepage "https://github.com/upamune/airule"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/airule/releases/download/v0.0.1/airule_Darwin_amd64.tar.gz"
      sha256 "65b5aa8579ad9213f174f2106e5e2eff11e10dd19acbaf393dd28c0183397f6d"

      def install
        bin.install "airule"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/airule/releases/download/v0.0.1/airule_Darwin_arm64.tar.gz"
      sha256 "5872a486e2eb835a96bb5ddbc309ec132017b843c69f338be129ecfe9b18b192"

      def install
        bin.install "airule"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/airule/releases/download/v0.0.1/airule_Linux_amd64.tar.gz"
        sha256 "e199859e804efcbc086e756f4b4d18ee020fe633439a5394bc9d5189740b91ef"

        def install
          bin.install "airule"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/airule/releases/download/v0.0.1/airule_Linux_arm64.tar.gz"
        sha256 "12dce761430fb5afcafbf26e318e43fb4650cd9ec6359ee21f1cffb544177074"

        def install
          bin.install "airule"
        end
      end
    end
  end
end
