# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gyz < Formula
  desc "gyz is a CLI tool for uploading images to Gyazo"
  homepage "https://github.com/upamune/gyz"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/upamune/gyz/releases/download/v0.4.0/gyz_Darwin_arm64.tar.gz"
      sha256 "617247d7ce79718d33edb553af19f70d2cd4f9356dcab0d47f5bae84956c0219"

      def install
        bin.install "gyz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/upamune/gyz/releases/download/v0.4.0/gyz_Darwin_x86_64.tar.gz"
      sha256 "cb8d0bb4b406e756c5fc3e7866613f4467692423f942075023e261d8d03e46b2"

      def install
        bin.install "gyz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/upamune/gyz/releases/download/v0.4.0/gyz_Linux_arm64.tar.gz"
      sha256 "a9b1c710d2bc90d44c9fe02964c21f1630afa36c3576f87bb0f87b349dfb3026"

      def install
        bin.install "gyz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/upamune/gyz/releases/download/v0.4.0/gyz_Linux_x86_64.tar.gz"
      sha256 "aebabe49bc551d5c4bd45737c05d01a4c547739f31d41b1ef44b56332a0ba032"

      def install
        bin.install "gyz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/upamune/gyz/releases/download/v0.4.0/gyz_Linux_armv6.tar.gz"
      sha256 "d20f41d8873aaa39139a87be4fe3f60f95f5f5b12ce52316a4d391dff3437e9e"

      def install
        bin.install "gyz"
      end
    end
  end
end
