# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MysqlExplainAnalyzer < Formula
  desc "mea is a CLI tool for analyzing MySQL explain"
  homepage "https://github.com/upamune/mea"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/mysql-explain-analyzer/releases/download/v0.3.0/mysql-explain-analyzer_Darwin_x86_64.tar.gz"
      sha256 "3cd57778ec1bceff19053e011c8ee775c44d0dfda93548870b099e3bd1562389"

      def install
        bin.install "mea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/mysql-explain-analyzer/releases/download/v0.3.0/mysql-explain-analyzer_Darwin_arm64.tar.gz"
      sha256 "e0ef1fde068fdb71fe2d011807141977f66788aeacb4bd30ec7529a77885b658"

      def install
        bin.install "mea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/mysql-explain-analyzer/releases/download/v0.3.0/mysql-explain-analyzer_Linux_x86_64.tar.gz"
      sha256 "09f8325073a763e0a91ae77dcf95b4f118ebceb74bcfd61532e548a8c1f1a250"

      def install
        bin.install "mea"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/upamune/mysql-explain-analyzer/releases/download/v0.3.0/mysql-explain-analyzer_Linux_armv6.tar.gz"
      sha256 "8830e562138e62fddb509da1374886f953681abd9b708a009cb4af5c0448e2fe"

      def install
        bin.install "mea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/upamune/mysql-explain-analyzer/releases/download/v0.3.0/mysql-explain-analyzer_Linux_arm64.tar.gz"
      sha256 "ab8ce5d67ac9bb5baa074a909d3a6f7a0fe847e2b09aa9ac8a5013a55459ce1c"

      def install
        bin.install "mea"
      end
    end
  end
end
