# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MysqlExplainAnalyzer < Formula
  desc "mea is a CLI tool for analyzing MySQL explain"
  homepage "https://github.com/upamune/mea"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/mysql-explain-analyzer/releases/download/v0.4.0/mysql-explain-analyzer_Darwin_x86_64.tar.gz"
      sha256 "39548c394cd42faea10f42c0fc1dc586d56f378b8550ab50cfc3ece091ba2654"

      def install
        bin.install "mea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/mysql-explain-analyzer/releases/download/v0.4.0/mysql-explain-analyzer_Darwin_arm64.tar.gz"
      sha256 "4211b06f5b41cb9ffe414d3c4976516ac8ab2676a067e2435a3887f0dda223da"

      def install
        bin.install "mea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/mysql-explain-analyzer/releases/download/v0.4.0/mysql-explain-analyzer_Linux_x86_64.tar.gz"
        sha256 "17bbc6f2681eb3b23ec856cf5c718c90d4abe090e331c4c1475ae59b3c673819"

        def install
          bin.install "mea"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/mysql-explain-analyzer/releases/download/v0.4.0/mysql-explain-analyzer_Linux_armv6.tar.gz"
        sha256 "f248c04273718c2b91c5dfda0f6b7a3c4d1eecaff591189a675ece9f420f1764"

        def install
          bin.install "mea"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/mysql-explain-analyzer/releases/download/v0.4.0/mysql-explain-analyzer_Linux_arm64.tar.gz"
        sha256 "a17d93da6985bb94a6c9b6f3ef53b1cbdc34a6c31176fd2c1ae3527238e7fc45"

        def install
          bin.install "mea"
        end
      end
    end
  end
end
