# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roomode < Formula
  desc "roomode is a CLI tool for managing custom modes for RooCode"
  homepage "https://github.com/upamune/roomode"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/roomode/releases/download/v0.0.2/roomode_Darwin_amd64.tar.gz"
      sha256 "3ab31e465793c89ea3f0f5354c20595850dde20675c6166c8f58a8053db0ae12"

      def install
        bin.install "roomode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/roomode/releases/download/v0.0.2/roomode_Darwin_arm64.tar.gz"
      sha256 "9d64276d3233918633d6a6dac92ebde57a18026e7b480b480325251bb3f28934"

      def install
        bin.install "roomode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/roomode/releases/download/v0.0.2/roomode_Linux_amd64.tar.gz"
        sha256 "201fe3c53f1b5b87dcad4d31738119607657e56deb9e681cf90c2df0a74d2418"

        def install
          bin.install "roomode"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/roomode/releases/download/v0.0.2/roomode_Linux_arm64.tar.gz"
        sha256 "bab2eb4117c5d9ffbc34b11ffc2efdca305f6ebf53285d3c311eac7527f1fc81"

        def install
          bin.install "roomode"
        end
      end
    end
  end
end
