# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roomode < Formula
  desc "roomode is a CLI tool for managing custom modes for RooCode"
  homepage "https://github.com/upamune/roomode"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/roomode/releases/download/v0.0.1/roomode_Darwin_amd64.tar.gz"
      sha256 "b5937f86f00b4c26200996cc437d7313472669bb4a65ec005eef59cfac2925e6"

      def install
        bin.install "roomode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/roomode/releases/download/v0.0.1/roomode_Darwin_arm64.tar.gz"
      sha256 "6e21686d392a4511cf3aa170996494faa8aac1bc654d9b2f29c6d6485ffa6e39"

      def install
        bin.install "roomode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/roomode/releases/download/v0.0.1/roomode_Linux_amd64.tar.gz"
        sha256 "fd089f8723031b1a2f0ad8a4779d860666ed93ccdc2089f6e18cd870800849b7"

        def install
          bin.install "roomode"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/roomode/releases/download/v0.0.1/roomode_Linux_arm64.tar.gz"
        sha256 "0c5db3e87a6279066fd8e7701cc966f1da496103802dd8aa927d09338a4bc66e"

        def install
          bin.install "roomode"
        end
      end
    end
  end
end
