# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Try < Formula
  desc "Ephemeral workspace manager"
  homepage "https://github.com/upamune/try-go"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/upamune/try-go/releases/download/v0.0.3/try_darwin_arm64.tar.gz"
      sha256 "74771198667dd855d6f4e79914d2d1c3dbab0234c9db331dcc184ec75ce003cd"

      def install
        bin.install "try"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/upamune/try-go/releases/download/v0.0.3/try_linux_amd64.tar.gz"
      sha256 "c179c9ad35258dd9cd7fb7da9a68f7b81818e5c7c8c193d8bf8da5ddfff9c88f"
      def install
        bin.install "try"
      end
    end
  end

  test do
    system "#{bin}/try", "--version"
  end
end
