# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Try < Formula
  desc "Ephemeral workspace manager"
  homepage "https://github.com/upamune/try-go"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/upamune/try-go/releases/download/v0.0.1/try_darwin_arm64.tar.gz"
      sha256 "94989eb060fe517f6361751b1689f48f4b9ab636e4c24ccb028b345915a632a9"

      def install
        bin.install "try"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/upamune/try-go/releases/download/v0.0.1/try_linux_amd64.tar.gz"
      sha256 "3f89afcd8216dbbbe586658edc6fbfee5709c39ef16f109109602154e6346f1a"
      def install
        bin.install "try"
      end
    end
  end

  test do
    system "#{bin}/try", "--version"
  end
end
