# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typereplacer < Formula
  desc "typereplacer is a CLI tool for rewriting struct fields' types based on a config."
  homepage "https://github.com/upamune/typereplacer"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/typereplacer/releases/download/v0.1.0/typereplacer_Darwin_x86_64.tar.gz"
      sha256 "5647bf867a95d45156ed9b73fd40721c9c808d70d3d923ea56ac259d06f3fbfc"

      def install
        bin.install "typereplacer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/typereplacer/releases/download/v0.1.0/typereplacer_Darwin_arm64.tar.gz"
      sha256 "9fcc81c740eacbf264cd10c63247d325e2705236c88e38dc3bd88c00aa4651cc"

      def install
        bin.install "typereplacer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/typereplacer/releases/download/v0.1.0/typereplacer_Linux_x86_64.tar.gz"
        sha256 "990dfdcadc5f0887491e85169a427a7cf718ed03e8cb46da1dbb3637efe6a651"

        def install
          bin.install "typereplacer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/typereplacer/releases/download/v0.1.0/typereplacer_Linux_arm64.tar.gz"
        sha256 "9e40f9a29c5bf07634945ac6cdd57e55599f5ed2f131a5b982a3fdefc828f397"

        def install
          bin.install "typereplacer"
        end
      end
    end
  end
end
