# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Typereplacer < Formula
  desc "typereplacer is a CLI tool for rewriting struct fields' types based on a config."
  homepage "https://github.com/upamune/typereplacer"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upamune/typereplacer/releases/download/v0.3.0/typereplacer_Darwin_x86_64.tar.gz"
      sha256 "2b1e85e89f0c9a10d6fca453077996ed1780b9821b0e965da760eecedae5bfee"

      def install
        bin.install "typereplacer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upamune/typereplacer/releases/download/v0.3.0/typereplacer_Darwin_arm64.tar.gz"
      sha256 "70ad0aa0ad126c524d9c2494a90ccaf3e63bdd4360f996408fc4f8a94bbafb37"

      def install
        bin.install "typereplacer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/typereplacer/releases/download/v0.3.0/typereplacer_Linux_x86_64.tar.gz"
        sha256 "ea7882174ceca6848db9190f01be0f9f587b37b678bd167c1a4394ad809c4d08"

        def install
          bin.install "typereplacer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/upamune/typereplacer/releases/download/v0.3.0/typereplacer_Linux_arm64.tar.gz"
        sha256 "b605f4ae7da6502713f75f04fcde4030e63c6e2610a02bf145e22765c2345625"

        def install
          bin.install "typereplacer"
        end
      end
    end
  end
end
